### ISSUE TITLE
Ambiguous metric names

### ISSUE THREAD

**Issue by dhamaris** [paperswithcode/paperswithcode-data#11]
Hi, I found that there are several metric names that are written differently along the tree, sometimes with a dash, sometimes with a space to separate words. These are the ones that I found:

ROC-AUC
F1-SCORE
PR-AUC
TOP-1 ACCURACY
TOP-5 ACCURACY
MACRO-F1
MICRO-F1

Thank you

**Comment by omarsar** [comment]
@dhamaris it seems like this is case. We will need to discuss this with our team about how we plan to clean things up. Thanks for reporting it.

**Comment by dhamaris** [comment]
Ok, thank you
