### ISSUE TITLE
Compressed data dump is outdated

### ISSUE THREAD

**Issue by my-master-za** [paperswithcode/paperswithcode-data#16]
Hi all!

We are having trouble retrieving the most recent PwC data from the compressed dump. It looks like the data was last updated on the 16th of September, and before that, we always were able to retrieve the fresh data on a daily basis.

Steps to verify the issue:

1. Check the paper and code links from the most recent papers on the PwC website here: https://paperswithcode.com/
2. Download the compressed data dump: https://production-media.paperswithcode.com/about/links-between-papers-and-code.json.gz
3. Unpack the data and make sure that the papers you saw at step (1) are not present in the dump.

Did PwC change policy on how often the downloadable dump would be updated? Any help is much appreciated.

Thanks!

**Comment by mkardas** [comment]
Hi Olga,

thanks for letting us know. The most recent dump is ready to be downloaded now. Nothing has changed and we will continue to publish the data on a daily basis.

Cheers,
Marcin
