### ISSUE TITLE
Wrong date in experiment 

### ISSUE THREAD

**Issue by dhamaris** [paperswithcode/paperswithcode-data#19]
Hi, evaluation-tables.json contains a wrong date for this paper:
https://ieeexplore.ieee.org/abstract/document/9363382
The date is 2121-03-01.
You can also see it here: https://paperswithcode.com/paper/a-deeppixbis-attentional-angular-margin-for

Can you please correct it?
Thank you

**Comment by rstojnic** [comment]
Thanks for reporting @dhamaris - fixed in the database, and should also be fixed in the next data dump later today.
