### ISSUE TITLE
Lipophilicity ambiguous relationship with Graph Regresion

### ISSUE THREAD

**Issue by dhamaris** [paperswithcode/paperswithcode-data#21]
Hello, while parsing data we found that Lipophilicity dataset appears twice in relationship to Graph Regresion task:
https://paperswithcode.com/sota/graph-regression-on-lipophilicity-1
https://paperswithcode.com/sota/graph-regression-on-lipophilicity

This is represented in our tree like this:
![image](https://user-images.githubusercontent.com/1392485/175902998-bcb1a2e9-99ae-489f-a7b6-de99fb65bb6d.png)

Will this be corrected or is it meant to be so?
Thank you

**Comment by mkardas** [comment]
Hi, thanks for letting us know. We will merge the two leaderboards.

**Comment by dhamaris** [comment]
Thank you! Please also check TOx21 that and other datasets that seem to have the same problem.
Thank you
