### ISSUE TITLE
Duplicate task (Speech Recognition | Automatic Speech Recognition)

### ISSUE THREAD

**Issue by thiborose** [paperswithcode/paperswithcode-data#26]
https://paperswithcode.com/task/speech-recognition

https://paperswithcode.com/task/automatic-speech-recognition

I believe those two tasks should be merged (or, if not, a description should be added to the Automatic Speech Recognition page. Currently no description available)

**Comment by alefnula** [comment]
According to our review team, these things should be held separate.
