### ISSUE TITLE
Do you have an active slack?

### ISSUE THREAD

**Issue by VladimirAlexiev** [paperswithcode/paperswithcode-data#30]
The two slack links at https://paperswithcode.com/about
(https://paperswithcode.slack.com/join/shared_invite/zt-265a18msm-Z3dOPw9EZH40IKZh8pNieA)
give this error: This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by jmelot** [comment]
fwiw, the slack I am on is still working. I just posted this issue in the general channel, hopefully someone can help you

**Comment by andrewkuanop** [comment]
Link updated!

**Comment by VladimirAlexiev** [comment]
Thanks! I joined.
For some reason I can access from a browser https://app.slack.com/client/TFGEZ65DE/CFW2LLWAZ,
but not from the desktop version.
Any ideas?

**Comment by alefnula** [comment]
Unfortunately no. I cannot reproduce the issue. For me the slack channel works from the app. If you still experiencing this issue please provide more details so I can look into it.

Hope this helps!
