### ISSUE TITLE
Relationship between papers and tasks

### ISSUE THREAD

**Issue by korakot** [paperswithcode/paperswithcode-data#4]
Currently, if I have a paper and want to know which tasks it's about, I can't do it easily.
I have to map all tasks → dataset → sota row → paper_url (abstract). 
Then reverse look up back.

However, some paper may not have an evaluation dataset. I can't lookup its task at all.
Like this one.
https://paperswithcode.com/paper/convolutional-generative-adversarial-networks

Can you distribute this relationship data between papers and tasks as well? I don't want to scrape Paper-With-Code for all those papers, just to get the task infos.

**Comment by rstojnic** [comment]
Hi @korakot - good point. I've now added tasks to papers in `papers-with-abstracts.json.gz`. It should be available in a couple of hours once the dump is regenerated and cache expires.

**Comment by korakot** [comment]
Thanks a lot. 🙏🙏🙏
