### ISSUE TITLE
Images/Thumbnails?

### ISSUE THREAD

**Issue by craze3** [paperswithcode/paperswithcode-data#6]
Is there a way to get the thumbnails / images used on your website, to use in addition to the rest of the data ?

BTW: This is a wonderful resource, thank you guys for sharing with the world!

**Comment by craze3** [comment]
@rstojnic Any ideas on how to get the images?

**Comment by alefnula** [comment]
Unfortunately not. We are very low on resources so I don't think this feature will be implemented in the near future.
