### ISSUE TITLE
Method information missing

### ISSUE THREAD

**Issue by malteos** [paperswithcode/paperswithcode-data#8]
Hi all,

are there data dumps available that contain method information as well? 

It seems that the dumps from https://paperswithcode.com/about have only the information on the dataset + task.

Best
Malte

**Comment by RJT1990** [comment]
Thanks, not sure we got around to this yet, I'll see if I can get done for you tomorrow!

**Comment by malteos** [comment]
If you do some changes to the data dump, it would be really handy if there are paper IDs, too. Or is `paper_url` equal to an ID?

**Comment by korakot** [comment]
I come to ask for this as well.

Congratulations on arXiv partnership!

**Comment by rstojnic** [comment]
Sorry for the delay everyone! This is now available to download here: https://paperswithcode.com/media/about/methods.json.gz

**Comment by korakot** [comment]
@rstojnic The file `methods.json.gz` only contains detail on each method. The link between paper-and-method is missing. 

Which papers use BERT method? I want to answer that. (without scraping)
