### ISSUE TITLE
Links between methods and papers

### ISSUE THREAD

**Issue by korakot** [paperswithcode/paperswithcode-data#9]
The recently released method data is useful. But please also provide links between methods and papers. Otherwise, I need to scrape it myself. 

Like [this colab](https://colab.fan/1yBzivRhT2Mm6BNKw7N8HNEZkveVZfkXI), with excerpt below.

```python
def list_papers(url):
     links = Soup(url).select('#papersTable td > a')
     return [a['href'] for a in links]
```

The colab notebook show my scraping of 5/878 methods. I don't want to load your server, so please dump the data out instead. Thanks a lot.

**Comment by rstojnic** [comment]
@alefnula Can you please add to the methods dump?

**Comment by malteos** [comment]
+1

**Comment by malteos** [comment]
Was this closed because it won't be fix? Because the links are still missing in the `methods.json`.

**Comment by alefnula** [comment]
@malteos The methods are added to the paper export. Every paper has a list of methods used in the paper.

**Comment by malteos** [comment]
Thanks! I really appreciate your work.
